#version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    container_name: loan_manager_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loan_manager
    ports:
      - "5433:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5433/loanmanager
      - NODE_ENV=production
    restart: always
volumes:
  postgres_data: 